In [1]:
#скачиваем ноутбук 10 с GitHub и запускаем его - он создаст все 45 csv
zapros = 'https://raw.githubusercontent.com/polina-orlova/hse_scraping_api_project_moex/refs/heads/feature/api/notebooks'

!wget -q {zapros}/10_export_csvs_45.ipynb

%run 10_export_csvs_45.ipynb

скачали с гитхаба все 9 колабов
Авторизация успешна
Cookie получен: True
создали parametrs.txt с такими параметрами:
enabled=true
level=INFO
filename=logs/logging_infa
format=%(asctime)s - %(levelname)s - %(lineno)d - %(message)s

Logging работает: уровень=INFO, файл=logs/logging_infa
Count of rows: 500
Count of rows after 500 rows: 500
Count of rows after 500 rows: 500
Count of rows after 1000 rows: 500
Count of rows after 1500 rows: 500
Count of rows after 2000 rows: 73
Count of rows after 2073 rows: 0
Total rows: 2073
Count of rows: 27
Полное название: Сбербанк России ПАО ао
ISIN: RU0009029540
Уровень листинга: 1
Count of rows: 6
Все дивиденты за 2018-01-01 - 2025-12-31: 6
Count of rows: 1
Последняя цена SBER: 320.16
Изменение к пред. закрытию: -0.19
Капитализация: 6911277271680
Count of rows: 19
SBER входит в IMOEX: True
Авторизация успешна
Cookie получен: True
создали parametrs.txt с такими параметрами:
enabled=true
level=INFO
filename=logs/logging_infa
format=%(asctime)s - %(levelname)s - %(lineno)d - %(message)s

Logging работает: уровень=INFO, файл=logs/logging_infa
Count of rows: 500
Count of rows after 500 rows: 500
Count of rows after 500 rows: 500
Count of rows after 1000 rows: 500
Count of rows after 1500 rows: 500
Count of rows after 2000 rows: 73
Count of rows after 2073 rows: 0
Total rows: 2073
Count of rows: 27
Полное название: "Газпром" (ПАО) ао
ISIN: RU0007661625
Уровень листинга: 1
Count of rows: 10
Все дивиденты за 2018-01-01 - 2025-12-31: 6
Count of rows: 1
Последняя цена GAZP: 131.89
Изменение к пред. закрытию: 0.88
Капитализация: 3122299616381
Count of rows: 19
GAZP входит в IMOEX: True
Авторизация успешна
Cookie получен: True
создали parametrs.txt с такими параметрами:
enabled=true
level=INFO
filename=logs/logging_infa
format=%(asctime)s - %(levelname)s - %(lineno)d - %(message)s

Logging работает: уровень=INFO, файл=logs/logging_infa
Count of rows: 500
Count of rows after 500 rows: 500
Count of rows after 500 rows: 500
Count of rows after 1000 rows: 500
Count of rows after 1500 rows: 500
Count of rows after 2000 rows: 73
Count of rows after 2073 rows: 0
Total rows: 2073
Count of rows: 27
Полное название: НК ЛУКОЙЛ (ПАО) - ао
ISIN: RU0009024277
Уровень листинга: 1
Count of rows: 25
Все дивиденты за 2018-01-01 - 2025-12-31: 14
Count of rows: 1
Последняя цена LKOH: 5807
Изменение к пред. закрытию: 0.29
Капитализация: 4023471479934
Count of rows: 21
LKOH входит в IMOEX: True
Авторизация успешна
Cookie получен: True
создали parametrs.txt с такими параметрами:
enabled=true
level=INFO
filename=logs/logging_infa
format=%(asctime)s - %(levelname)s - %(lineno)d - %(message)s

Logging работает: уровень=INFO, файл=logs/logging_infa
Count of rows: 500
Count of rows after 500 rows: 500
Count of rows after 500 rows: 500
Count of rows after 1000 rows: 500
Count of rows after 1500 rows: 500
Count of rows after 2000 rows: 73
Count of rows after 2073 rows: 0
Total rows: 2073
Count of rows: 27
Полное название: ПАО НК Роснефть
ISIN: RU000A0J2Q06
Уровень листинга: 1
Count of rows: 19
Все дивиденты за 2018-01-01 - 2025-12-31: 14
Count of rows: 1
Последняя цена ROSN: 512.9
Изменение к пред. закрытию: 0.18
Капитализация: 5435805402339.3
Count of rows: 20
ROSN входит в IMOEX: True
Авторизация успешна
Cookie получен: True
создали parametrs.txt с такими параметрами:
enabled=true
level=INFO
filename=logs/logging_infa
format=%(asctime)s - %(levelname)s - %(lineno)d - %(message)s

Logging работает: уровень=INFO, файл=logs/logging_infa
Count of rows: 500
Count of rows after 500 rows: 500
Count of rows after 500 rows: 500
Count of rows after 1000 rows: 500
Count of rows after 1500 rows: 500
Count of rows after 2000 rows: 72
Count of rows after 2072 rows: 0
Total rows: 2072
Count of rows: 27
Полное название: Мобильные ТелеСистемы ПАО ао
ISIN: RU0007775219
Уровень листинга: 1
Count of rows: 13
Все дивиденты за 2018-01-01 - 2025-12-31: 13
Count of rows: 1
Последняя цена MTSS: 227.45
Изменение к пред. закрытию: -0.11
Капитализация: 454531889233.75
Count of rows: 20
MTSS входит в IMOEX: True
Авторизация успешна
Cookie получен: True
создали parametrs.txt с такими параметрами:
enabled=true
level=INFO
filename=logs/logging_infa
format=%(asctime)s - %(levelname)s - %(lineno)d - %(message)s

Logging работает: уровень=INFO, файл=logs/logging_infa
Count of rows: 500
Count of rows after 500 rows: 500
Count of rows after 500 rows: 500
Count of rows after 1000 rows: 500
Count of rows after 1500 rows: 500
Count of rows after 2000 rows: 69
Count of rows after 2069 rows: 0
Total rows: 2069
Count of rows: 27
Полное название: ГМК "Нор.Никель" ПАО ао
ISIN: RU0007288411
Уровень листинга: 1
Count of rows: 21
Все дивиденты за 2018-01-01 - 2025-12-31: 11
Count of rows: 1
Последняя цена GMKN: 152.54
Изменение к пред. закрытию: 0.01
Капитализация: 2331778257838
Count of rows: 23
GMKN входит в IMOEX: True
Авторизация успешна
Cookie получен: True
создали parametrs.txt с такими параметрами:
enabled=true
level=INFO
filename=logs/logging_infa
format=%(asctime)s - %(levelname)s - %(lineno)d - %(message)s

Logging работает: уровень=INFO, файл=logs/logging_infa
Count of rows: 500
Count of rows after 500 rows: 500
Count of rows after 500 rows: 500
Count of rows after 1000 rows: 500
Count of rows after 1500 rows: 500
Count of rows after 2000 rows: 73
Count of rows after 2073 rows: 0
Total rows: 2073
Count of rows: 27
Полное название: "Магнит" ПАО ао
ISIN: RU000A0JKQU8
Уровень листинга: 3
Count of rows: 24
Все дивиденты за 2018-01-01 - 2025-12-31: 11
Count of rows: 1
Последняя цена MGNT: 3207
Изменение к пред. закрытию: -0.93
Капитализация: 326829715485
Count of rows: 18
MGNT входит в IMOEX: True
Авторизация успешна
Cookie получен: True
создали parametrs.txt с такими параметрами:
enabled=true
level=INFO
filename=logs/logging_infa
format=%(asctime)s - %(levelname)s - %(lineno)d - %(message)s

Logging работает: уровень=INFO, файл=logs/logging_infa
Count of rows: 500
Count of rows after 500 rows: 500
Count of rows after 500 rows: 500
Count of rows after 1000 rows: 500
Count of rows after 1500 rows: 500
Count of rows after 2000 rows: 73
Count of rows after 2073 rows: 0
Total rows: 2073
Count of rows: 27
Полное название: АЛРОСА ПАО ао
ISIN: RU0007252813
Уровень листинга: 1
Count of rows: 14
Все дивиденты за 2018-01-01 - 2025-12-31: 10
Count of rows: 1
Последняя цена ALRS: 37.75
Изменение к пред. закрытию: -1.77
Капитализация: 278027452532.5
Count of rows: 23
ALRS входит в IMOEX: True
Авторизация успешна
Cookie получен: True
создали parametrs.txt с такими параметрами:
enabled=true
level=INFO
filename=logs/logging_infa
format=%(asctime)s - %(levelname)s - %(lineno)d - %(message)s

Logging работает: уровень=INFO, файл=logs/logging_infa
Count of rows: 500
Count of rows after 500 rows: 500
Count of rows after 500 rows: 500
Count of rows after 1000 rows: 500
Count of rows after 1500 rows: 500
Count of rows after 2000 rows: 69
Count of rows after 2069 rows: 0
Total rows: 2069
Count of rows: 27
Полное название: ао ПАО Банк ВТБ
ISIN: RU000A0JP5V6
Уровень листинга: 1
Count of rows: 11
Все дивиденты за 2018-01-01 - 2025-12-31: 6
Count of rows: 1
Последняя цена VTBR: 85.905
Изменение к пред. закрытию: -0.07
Капитализация: 568727032515.21
Count of rows: 17
VTBR входит в IMOEX: True

In [2]:
import pandas as pd

In [3]:
df_SBER = pd.read_csv('moex_csvs/candles_SBER.csv')
df_GAZP = pd.read_csv('moex_csvs/candles_GAZP.csv')
df_LKOH = pd.read_csv('moex_csvs/candles_LKOH.csv')
df_ROSN = pd.read_csv('moex_csvs/candles_ROSN.csv')
df_MTSS = pd.read_csv('moex_csvs/candles_MTSS.csv')
df_GMKN = pd.read_csv('moex_csvs/candles_GMKN.csv')
df_MGNT = pd.read_csv('moex_csvs/candles_MGNT.csv')
df_ALRS = pd.read_csv('moex_csvs/candles_ALRS.csv')
df_VTBR = pd.read_csv('moex_csvs/candles_VTBR.csv')

df_vse_candles = pd.concat([df_SBER, df_GAZP, df_LKOH, df_ROSN, df_MTSS, df_GMKN, df_MGNT, df_ALRS, df_VTBR], ignore_index=True)
df_vse_candles['begin'] = pd.to_datetime(df_vse_candles['begin'])
df_vse_candles

,open,close,high,low,value,volume,begin,end,ticker
0,226.88,231.90,232.70,226.35,7.965493e+09,34549620,2018-01-03,2018-01-03 23:59:59,SBER
1,232.13,238.80,239.50,231.00,1.263668e+10,53598520,2018-01-04,2018-01-04 23:59:59,SBER
2,238.89,238.60,239.95,236.70,7.522345e+09,31579190,2018-01-05,2018-01-05 23:59:59,SBER
3,239.03,240.40,243.76,239.01,1.283838e+10,53172330,2018-01-09,2018-01-09 23:59:59,SBER
4,240.40,237.76,241.25,237.06,9.385277e+09,39371720,2018-01-10,2018-01-10 23:59:59,SBER
...,...,...,...,...,...,...,...,...,...
18643,71.40,72.92,73.10,71.30,5.230881e+09,72258291,2025-12-26,2025-12-26 23:59:58,VTBR
18644,73.01,72.95,73.15,72.77,6.305460e+08,8640898,2025-12-27,2025-12-27 23:59:57,VTBR
18645,72.83,72.92,73.07,72.60,5.098772e+08,6997767,2025-12-28,2025-12-28 23:59:57,VTBR
18646,73.29,72.17,73.95,71.80,6.656170e+09,91335409,2025-12-29,2025-12-29 23:59:59,VTBR
18647,72.08,72.22,72.57,72.08,2.928540e+09,40481842,2025-12-30,2025-12-30 23:59:58,VTBR

In [4]:
df_infa_SBER = pd.read_csv('moex_csvs/infa_SBER.csv')
df_infa_GAZP = pd.read_csv('moex_csvs/infa_GAZP.csv')
df_infa_LKOH = pd.read_csv('moex_csvs/infa_LKOH.csv')
df_infa_ROSN = pd.read_csv('moex_csvs/infa_ROSN.csv')
df_infa_MTSS = pd.read_csv('moex_csvs/infa_MTSS.csv')
df_infa_GMKN = pd.read_csv('moex_csvs/infa_GMKN.csv')
df_infa_MGNT = pd.read_csv('moex_csvs/infa_MGNT.csv')
df_infa_ALRS = pd.read_csv('moex_csvs/infa_ALRS.csv')
df_infa_VTBR = pd.read_csv('moex_csvs/infa_VTBR.csv')

df_vse_infa = pd.concat([df_infa_SBER, df_infa_GAZP, df_infa_LKOH, df_infa_ROSN, df_infa_MTSS, df_infa_GMKN, df_infa_MGNT, df_infa_ALRS, df_infa_VTBR], ignore_index=True)
df_vse_infa

,index,SECID,ISSUENAME,NAME,SHORTNAME,ISIN,REGNUMBER,ISSUESIZE,FACEVALUE,FACEUNIT,...,MORNINGSESSION,EVENINGSESSION,WEEKENDSESSION,REGISTRY_DATE,TYPENAME,GROUP,TYPE,GROUPNAME,EMITTER_ID,ticker
0,value,SBER,Акции обыкновенные,Сбербанк России ПАО ао,Сбербанк,RU0009029540,10301481B,21586948000,3.000,SUR,...,1,1,1,2007-07-11,Акция обыкновенная,stock_shares,common_share,Акции,484,SBER
1,value,GAZP,Акции обыкновенные,"""Газпром"" (ПАО) ао",ГАЗПРОМ ао,RU0007661625,1-02-00028-A,23673512900,5.000,SUR,...,1,1,1,1998-12-30,Акция обыкновенная,stock_shares,common_share,Акции,711,GAZP
2,value,LKOH,Акции обыкновенные,НК ЛУКОЙЛ (ПАО) - ао,ЛУКОЙЛ,RU0009024277,1-01-00077-A,692865762,0.025,SUR,...,1,1,1,2003-06-25,Акция обыкновенная,stock_shares,common_share,Акции,770,LKOH
3,value,ROSN,Акции обыкновенные,ПАО НК Роснефть,Роснефть,RU000A0J2Q06,1-02-00122-A,10598177817,0.010,SUR,...,1,1,1,2005-09-29,Акция обыкновенная,stock_shares,common_share,Акции,651,ROSN
4,value,MTSS,Акции обыкновенные,Мобильные ТелеСистемы ПАО ао,МТС-ао,RU0007775219,1-01-04715-A,1998381575,0.100,SUR,...,1,1,1,2004-01-22,Акция обыкновенная,stock_shares,common_share,Акции,1352,MTSS
5,value,GMKN,акция обыкновенная бездокументарная именная,"ГМК ""Нор.Никель"" ПАО ао",ГМКНорНик,RU0007288411,1-01-40155-F,15286339700,0.010,SUR,...,1,1,1,2006-12-12,Акция обыкновенная,stock_shares,common_share,Акции,1399,GMKN
6,value,MGNT,акции обыкновенные именные бездокументарные,"""Магнит"" ПАО ао",Магнит ао,RU000A0JKQU8,1-01-60525-P,101911355,0.010,SUR,...,1,1,1,2004-03-04,Акция обыкновенная,stock_shares,common_share,Акции,886,MGNT
7,value,ALRS,акции обыкновенные,АЛРОСА ПАО ао,АЛРОСА ао,RU0007252813,1-03-40046-N,7364965630,0.500,SUR,...,1,1,1,2011-08-25,Акция обыкновенная,stock_shares,common_share,Акции,1670,ALRS
8,value,VTBR,Акции обыкновенные,ао ПАО Банк ВТБ,ВТБ ао,RU000A0JP5V6,10401000B,6620418282,50.000,SUR,...,1,1,1,2006-09-29,Акция обыкновенная,stock_shares,common_share,Акции,269,VTBR

In [5]:
df_diva_SBER = pd.read_csv('moex_csvs/diva_SBER.csv')
df_diva_GAZP = pd.read_csv('moex_csvs/diva_GAZP.csv')
df_diva_LKOH = pd.read_csv('moex_csvs/diva_LKOH.csv')
df_diva_ROSN = pd.read_csv('moex_csvs/diva_ROSN.csv')
df_diva_MTSS = pd.read_csv('moex_csvs/diva_MTSS.csv')
df_diva_GMKN = pd.read_csv('moex_csvs/diva_GMKN.csv')
df_diva_MGNT = pd.read_csv('moex_csvs/diva_MGNT.csv')
df_diva_ALRS = pd.read_csv('moex_csvs/diva_ALRS.csv')
df_diva_VTBR = pd.read_csv('moex_csvs/diva_VTBR.csv')

df_vse_diva = pd.concat([df_diva_SBER, df_diva_GAZP, df_diva_LKOH, df_diva_ROSN, df_diva_MTSS, df_diva_GMKN, df_diva_MGNT, df_diva_ALRS, df_diva_VTBR], ignore_index=True)
df_vse_diva['registryclosedate'] = pd.to_datetime(df_vse_diva['registryclosedate'])
df_vse_diva

    index secid          isin registryclosedate      value currencyid ticker
0       0  SBER  RU0009029540        2019-06-13  16.000000        RUB   SBER
1       1  SBER  RU0009029540        2020-10-05  18.700000        RUB   SBER
2       2  SBER  RU0009029540        2021-05-12  18.700000        RUB   SBER
3       3  SBER  RU0009029540        2023-05-11  25.000000        RUB   SBER
4       4  SBER  RU0009029540        2024-07-11  33.300000        RUB   SBER
..    ...   ...           ...               ...        ...        ...    ...
86      6  VTBR  RU000A0JP5V6        2019-06-24   0.001099        RUB   VTBR
87      7  VTBR  RU000A0JP5V6        2020-10-05   0.000773        RUB   VTBR
88      8  VTBR  RU000A0JP5V6        2021-06-22   0.000017        RUB   VTBR
89      9  VTBR  RU000A0JP5V6        2021-07-15   0.000017        RUB   VTBR
90     10  VTBR  RU000A0JP5V6        2025-07-11  25.580000        RUB   VTBR

[91 rows x 7 columns]

In [6]:
df_markdata_SBER = pd.read_csv('moex_csvs/markdata_SBER.csv')
df_markdata_GAZP = pd.read_csv('moex_csvs/markdata_GAZP.csv')
df_markdata_LKOH = pd.read_csv('moex_csvs/markdata_LKOH.csv')
df_markdata_ROSN = pd.read_csv('moex_csvs/markdata_ROSN.csv')
df_markdata_MTSS = pd.read_csv('moex_csvs/markdata_MTSS.csv')
df_markdata_GMKN = pd.read_csv('moex_csvs/markdata_GMKN.csv')
df_markdata_MGNT = pd.read_csv('moex_csvs/markdata_MGNT.csv')
df_markdata_ALRS = pd.read_csv('moex_csvs/markdata_ALRS.csv')
df_markdata_VTBR = pd.read_csv('moex_csvs/markdata_VTBR.csv')

df_vse_markdata = pd.concat([df_markdata_SBER, df_markdata_GAZP, df_markdata_LKOH, df_markdata_ROSN, df_markdata_MTSS, df_markdata_GMKN, df_markdata_MGNT, df_markdata_ALRS, df_markdata_VTBR], ignore_index=True)
df_vse_markdata

,ticker,LAST,LASTTOPREVPRICE,BID,OFFER,OPEN,HIGH,LOW,WAPRICE,NUMTRADES,VOLTODAY,VALTODAY,ISSUECAPITALIZATION,UPDATETIME
0,SBER,320.160,-0.19,NaN,NaN,321.00,322.00,319.510,321.000,106329,21758167,6984138254,6.911277e+12,23:50:21
1,GAZP,131.890,0.88,NaN,NaN,130.74,132.13,130.530,131.490,91643,64854220,8527393431,3.122300e+12,23:50:21
2,LKOH,5807.000,0.29,NaN,NaN,5790.00,5848.00,5723.000,5788.000,55870,1169245,6767437496,4.023471e+12,23:50:21
3,ROSN,512.900,0.18,NaN,NaN,511.00,514.40,505.500,510.350,90265,14411161,7354379925,5.435805e+12,23:50:21
4,MTSS,227.450,-0.11,NaN,NaN,228.00,228.50,227.000,227.800,22249,2228020,507571781,4.545319e+11,23:50:21
5,GMKN,152.540,0.01,NaN,NaN,152.50,154.50,152.320,153.640,28913,9283310,1426024687,2.331778e+12,23:50:21
6,MGNT,3207.000,-0.93,NaN,NaN,3240.00,3259.50,3201.500,3221.500,6592,106574,343335778,3.268297e+11,23:50:21
7,ALRS,37.750,-1.77,NaN,NaN,38.52,38.54,37.680,38.060,17199,13108140,498943157,2.780275e+11,23:50:21
8,VTBR,85.905,-0.07,NaN,NaN,86.17,86.85,85.725,86.365,83515,35982247,3107351735,5.687270e+11,23:50:21

In [7]:
df_idishka_SBER = pd.read_csv('moex_csvs/idishka_SBER.csv')
df_idishka_GAZP = pd.read_csv('moex_csvs/idishka_GAZP.csv')
df_idishka_LKOH = pd.read_csv('moex_csvs/idishka_LKOH.csv')
df_idishka_ROSN = pd.read_csv('moex_csvs/idishka_ROSN.csv')
df_idishka_MTSS = pd.read_csv('moex_csvs/idishka_MTSS.csv')
df_idishka_GMKN = pd.read_csv('moex_csvs/idishka_GMKN.csv')
df_idishka_MGNT = pd.read_csv('moex_csvs/idishka_MGNT.csv')
df_idishka_ALRS = pd.read_csv('moex_csvs/idishka_ALRS.csv')
df_idishka_VTBR = pd.read_csv('moex_csvs/idishka_VTBR.csv')

df_vse_idishka = pd.concat([df_idishka_SBER, df_idishka_GAZP, df_idishka_LKOH, df_idishka_ROSN, df_idishka_MTSS, df_idishka_GMKN, df_idishka_MGNT, df_idishka_ALRS, df_idishka_VTBR], ignore_index=True)
df_vse_idishka

,SECID,SHORTNAME,FROM,TILL,CURRENTVALUE,LASTCHANGEPRC,LASTCHANGE,ticker
0,EPSI,Субиндекс акций,2011-11-21,2026-03-20,1663.37,-0.12,-2.01,SBER
1,ESGI,Индекс МосБиржи Рейтинги УР,2026-02-16,2026-03-20,992.11,0.33,3.24,SBER
2,IMOEXCNY,Индекс МосБиржи в юанях,2024-09-24,2026-03-20,1098.66,3.61,38.28,SBER
3,IMOEXW,IMOEXW,2023-01-16,2026-03-20,2877.93,-0.13,-3.65,SBER
4,MESG,Индекс МосБиржи-RAEX ESG,2023-12-22,2026-03-20,982.21,-0.26,-2.54,SBER
...,...,...,...,...,...,...,...,...
175,IMOEX2,Индекс МосБиржи (все сессии),2020-06-22,2026-03-20,2872.42,0.12,3.43,VTBR
176,MOEX10,Индекс МосБиржи 10,2008-05-27,2026-03-20,5582.39,-0.08,-4.60,VTBR
177,MOEXBMI,Индекс широкого рынка,2011-12-30,2026-03-20,2053.34,-0.15,-3.13,VTBR
178,MOEXFN,Индекс финансов,2007-07-02,2026-03-20,9783.05,0.30,28.85,VTBR
179,MRBC,Индекс МосБиржи 15,2019-01-21,2026-03-20,1446.40,-0.12,-1.80,VTBR

In [8]:
df_mega = df_vse_candles.merge(df_vse_infa, on='ticker')
df_mega = df_mega.merge(df_vse_markdata, on='ticker')
df_mega

,open,close,high,low,value,volume,begin,end,ticker,index,...,OFFER,OPEN,HIGH,LOW,WAPRICE,NUMTRADES,VOLTODAY,VALTODAY,ISSUECAPITALIZATION,UPDATETIME
0,226.88,231.90,232.70,226.35,7.965493e+09,34549620,2018-01-03,2018-01-03 23:59:59,SBER,value,...,NaN,321.00,322.00,319.510,321.000,106329,21758167,6984138254,6.911277e+12,23:50:21
1,232.13,238.80,239.50,231.00,1.263668e+10,53598520,2018-01-04,2018-01-04 23:59:59,SBER,value,...,NaN,321.00,322.00,319.510,321.000,106329,21758167,6984138254,6.911277e+12,23:50:21
2,238.89,238.60,239.95,236.70,7.522345e+09,31579190,2018-01-05,2018-01-05 23:59:59,SBER,value,...,NaN,321.00,322.00,319.510,321.000,106329,21758167,6984138254,6.911277e+12,23:50:21
3,239.03,240.40,243.76,239.01,1.283838e+10,53172330,2018-01-09,2018-01-09 23:59:59,SBER,value,...,NaN,321.00,322.00,319.510,321.000,106329,21758167,6984138254,6.911277e+12,23:50:21
4,240.40,237.76,241.25,237.06,9.385277e+09,39371720,2018-01-10,2018-01-10 23:59:59,SBER,value,...,NaN,321.00,322.00,319.510,321.000,106329,21758167,6984138254,6.911277e+12,23:50:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18643,71.40,72.92,73.10,71.30,5.230881e+09,72258291,2025-12-26,2025-12-26 23:59:58,VTBR,value,...,NaN,86.17,86.85,85.725,86.365,83515,35982247,3107351735,5.687270e+11,23:50:21
18644,73.01,72.95,73.15,72.77,6.305460e+08,8640898,2025-12-27,2025-12-27 23:59:57,VTBR,value,...,NaN,86.17,86.85,85.725,86.365,83515,35982247,3107351735,5.687270e+11,23:50:21
18645,72.83,72.92,73.07,72.60,5.098772e+08,6997767,2025-12-28,2025-12-28 23:59:57,VTBR,value,...,NaN,86.17,86.85,85.725,86.365,83515,35982247,3107351735,5.687270e+11,23:50:21
18646,73.29,72.17,73.95,71.80,6.656170e+09,91335409,2025-12-29,2025-12-29 23:59:59,VTBR,value,...,NaN,86.17,86.85,85.725,86.365,83515,35982247,3107351735,5.687270e+11,23:50:21
18647,72.08,72.22,72.57,72.08,2.928540e+09,40481842,2025-12-30,2025-12-30 23:59:58,VTBR,value,...,NaN,86.17,86.85,85.725,86.365,83515,35982247,3107351735,5.687270e+11,23:50:21

In [9]:
df_vse_diva.to_csv('vse_dividends.csv', index=False)
df_vse_idishka.to_csv('vse_indices.csv', index=False)
df_mega.to_csv('mega_dataset.csv', index=False) #тут у нас candels, infa, marketdata