In [1]:
 import pandas as pd

In [2]:
a = pd.read_csv('rbc_ALRS.csv')
a

,news_id,ticker,url,title,published_at,text,category,sentiment_positive,sentiment_negative,sentiment_neutral
0,mts-bank-private-voshel-v-spisok-luchshih-bank...,MTSS,https://companies.rbc.ru/news/H0nXAx8uGq/mts-b...,МТС Банк Private вошел в список лучших банков ...,NaN,NaN,Не определена,NaN,NaN,NaN
1,685023957a8aa93a0103b841,MTSS,https://spb.plus.rbc.ru/news/685023957a8aa93a0...,Структурная перезагрузка,2025-06-17 16:16:19,В географически и логистически оторванном от к...,Тенденции,0.0798,0.0798,0.8404
2,67cacfbd9a79472db2261dbd,MTSS,https://www.rbc.ru/life/news/67cacfbd9a79472db...,"Каждый четвертый мужчина уверен, что не поздра...",2025-03-07 11:06:23,"SuperJob: каждый четвертый мужчина уверен, что...",Не определена,0.1506,0.1506,0.6988
3,67ee2b879a79474dd13bb3db,MTSS,https://pro.rbc.ru/demo/67ee2b879a79474dd13bb3db,Краха не избежать. Почему массовые увольнения ...,2025-04-08 07:01:07,NaN,Не определена,NaN,NaN,NaN
4,67cad2619a79473aaa0f2a5b,MTSS,https://www.rbc.ru/quote/news/article/67cad261...,Брокеры составили портрет среднестатистической...,2025-03-08 09:00:22,Российские женщины-инвесторы оказались успешне...,Новости,0.1065,0.1065,0.7871
...,...,...,...,...,...,...,...,...,...,...
1494,68b1b8ea9a7947a8b33f1e4a,MTSS,https://rostov.rbc.ru/rostov/freenews/68b1b8ea...,Число транзитных туристов в Ростовской области...,2025-08-29 17:29:11,Через Ростовскую область в 2024 году транзитом...,Не определена,0.1004,0.1004,0.7992
1495,697c8d649a7947db0ab13811,MTSS,https://pro.rbc.ru/demo/697c8d649a7947db0ab13811,ФСБ ужесточила доступ к «белым спискам» для ба...,2026-02-02 11:09:12,NaN,Не определена,NaN,NaN,NaN
1496,afk-sistema-razvivaet-sotsialnoe-partnerstvo-s...,MTSS,https://companies.rbc.ru/news/dvVuZ44GKZ/afk-s...,АФК «Система» развивает социальное партнерство...,NaN,NaN,Не определена,NaN,NaN,NaN
1497,6970486d9a794724b21e1a44,MTSS,https://nsk.rbc.ru/nsk/21/01/2026/6970486d9a79...,МТС: в морозы новосибирцы чаще работали из дома,2026-01-21 12:23:47,"Во время тридцатиградусных морозов, которые в ...",Не определена,0.1176,0.1176,0.7649
1498,mts-bank-rasshiryaet-set-otdelenij-v-sankt-pet...,MTSS,https://companies.rbc.ru/news/H4wo8rVAoo/mts-b...,МТС Банк расширяет сеть отделений в Санкт-Пете...,NaN,NaN,Не определена,NaN,NaN,NaN

In [3]:
b = pd.read_csv('rbc_GAZP.csv')
b

,news_id,ticker,url,title,published_at,text,category,sentiment_positive,sentiment_negative,sentiment_neutral
0,683850c39a7947476769e180,GMKN,https://www.rbc.ru/quote/news/article/683850c3...,Минфин оценил массовый отказ компаний от дивид...,2025-06-18 13:57:46,В Минфине впервые прокомментировали массовый о...,Новости,0.2406,0.2406,0.5188
1,gruppa-fingo-otsenivaet-ryinok-gazoochistki-v-...,GMKN,https://companies.rbc.ru/news/ndsWEhm0Az/grupp...,Группа ФИНГО оценивает рынок газоочистки в 127...,NaN,NaN,Не определена,NaN,NaN,NaN
2,633bbf279a7947850ec82b61,GMKN,https://pro.rbc.ru/demo/633bbf279a7947850ec82b61,Почему решение «Русала» о выплате дивидендов н...,2022-10-05 11:55:09,NaN,Не определена,NaN,NaN,NaN
3,5e3d38fa9a79473c61e9377e,GMKN,https://www.rbc.ru/quote/news/article/5e3d38fa...,Топ-5 привлекательных российских акций от Bank...,2020-02-11 11:07:59,В Bank of America позитивно оценили перспектив...,Не определена,0.0800,0.0800,0.8400
4,6193fe2a9a794700cad2ab0b,GMKN,https://www.rbc.ru/business/18/11/2021/6193fe2...,Рейтинг крупнейших компаний России РБК 500: кл...,2021-11-18 10:00:18,Совокупная выручка 500 крупнейших компаний Рос...,Не определена,0.2072,0.2072,0.5856
...,...,...,...,...,...,...,...,...,...,...
1489,68b80c159a7947c5081efffd,GMKN,https://www.rbc.ru/crypto/news/68b80c159a7947c...,Минфин предложил снизить требования к участник...,2025-09-03 14:09:39,Минфин России предложил снизить требования для...,Регулирование,0.0701,0.0701,0.8597
1490,5de8fff39a79470b36b2925c,GMKN,https://www.rbc.ru/business/06/12/2019/5de8fff...,«Норникель» и «Газпром нефть» арендуют ледокол...,2019-12-06 10:00:53,«Норникель» заключил соглашение с «Атомфлотом»...,Не определена,0.0640,0.0640,0.8719
1491,5dfdaec69a7947003498366e,GMKN,https://www.rbc.ru/economics/21/12/2019/5dfdae...,Потанин сравнил экономические реформы 1990-х г...,2019-12-21 08:34:10,Экономические реформы в России в 1990-х годах ...,Не определена,0.2456,0.5088,0.2456
1492,608a77fd2ae596154df27f20,GMKN,https://www.rbc.ru/quote/news/article/608a77fd...,Прибыль «Газпрома» упала на 89% в 2020 году,2021-04-29 13:15:50,Москва («Рейтер»). Российский газовый концерн«...,Новости,0.0986,0.8029,0.0986
1493,6447a7ed9a794769d1c0a96f,GMKN,https://www.rbc.ru/quote/news/article/6447a7ed...,БКС назвал лучшие дивидендные акции на ближайш...,2023-04-25 15:51:04,Дивиденды— это ключевая тема российского фондо...,Новости,0.0607,0.0607,0.8786

In [4]:
c = pd.read_csv('rbc_GMKN.csv')
c

,news_id,ticker,url,title,published_at,text,category,sentiment_positive,sentiment_negative,sentiment_neutral
0,699345359a79470a09fba8d4,SBER,https://www.rbc.ru/radio/16/02/2026/699345359a...,"Ян Арт — про IPO, звездные рейтинги и торги ан...",2026-02-16 19:31:01,• 01:49 Уолл-стрит и голубые фишки• 04:00 Как ...,Не определена,0.0746,0.0746,0.8507
1,69a0410e9a79473c9532f6bd,SBER,https://www.rbc.ru/politics/26/02/2026/69a0410...,Путин создал комиссию по вопросам развития тех...,2026-02-26 15:54:26,Комиссия по вопросам развития технологий искус...,Не определена,0.0549,0.0549,0.8902
2,692820d39a79476c14f31858,SBER,https://realty.rbc.ru/news/692820d39a79476c14f...,Подскочила на 20%: как вырастет оценка нежилых...,2025-11-27 16:33:43,Правительство Москвы утвердило перечень нежилы...,Деньги,0.0862,0.0862,0.8276
3,692da42b7a8aa90cc3762ef4,SBER,https://spb.plus.rbc.ru/pressrelease/692da42b7...,Сбер проведет «День инвестора» и представит но...,2025-12-01 18:55:06,Событие «Сделано в Сбере» объединит традиционн...,Пресс-релизы,0.0619,0.0619,0.8761
4,697b527e9a79474e8d2bb6ee,SBER,https://www.rbc.ru/quote/news/article/697b527e...,В SberCIB понизили прогноз по курсу доллара в ...,2026-01-29 17:08:23,Материал носит исключительно ознакомительный х...,Новости,0.1170,0.1170,0.7659
...,...,...,...,...,...,...,...,...,...,...
1494,698cdc6e9a794703d90f272d,SBER,https://www.rbc.ru/economics/12/02/2026/698cdc...,Экс-чиновники ответили Грефу на идею о реформе...,2026-02-12 06:01:19,Государственная должность не должна рассматрив...,Не определена,0.1348,0.1348,0.7304
1495,69903bef9a794726e4f40f7a,SBER,https://www.rbc.ru/rbcfreenews/69903bef9a79472...,Рябков заявил о возможности БРИКС ответить на ...,2026-02-14 13:10:31,"Рябков: БРИКС создает альтернативу всему, что ...",Не определена,0.1948,0.6104,0.1948
1496,68d5283c9a79470e6325965a,SBER,https://www.rbc.ru/crypto/news/68d5283c9a79470...,«Неквалам» откроют доступ к ЦФА с привязкой к ...,2025-09-25 14:52:19,Банк России намерен с 1 января 2026 года допус...,ЦФА,0.0314,0.0314,0.9371
1497,691b1bc47a8aa9043ddc339e,SBER,https://spb.plus.rbc.ru/pressrelease/691b1bc47...,"Сбер презентовал модель ИИ, которая выявляет р...",2025-11-17 16:45:07,"Индустрия здоровья Сбера, центр практического ...",Пресс-релизы,0.0684,0.0684,0.8631
1498,ne-prosto-pedagogi-kak-repetitoryi-podderzhiva...,SBER,https://companies.rbc.ru/news/48ToAvcQ2r/ne-pr...,Не просто педагоги: как репетиторы поддерживаю...,NaN,NaN,Не определена,NaN,NaN,NaN

In [5]:
d = pd.read_csv('rbc_LKOH.csv')
d

,news_id,ticker,url,title,published_at,text,category,sentiment_positive,sentiment_negative,sentiment_neutral
0,ekaterina-ledokol-bolshie-dannyie-na-vef-i-gvs,MGNT,https://companies.rbc.ru/news/CVzTYn684i/ekate...,Екатерина Ледокол: Большие данные на ВЭФ и GVS,NaN,NaN,Не определена,NaN,NaN,NaN
1,6725be089a794748e7ddd332,MGNT,https://www.rbc.ru/life/news/6725be089a794748e...,Раковины черноморских моллюсков оказались поле...,2024-11-02 07:10:12,РАН: черноморские моллюски оказались «накопите...,Не определена,0.0647,0.0647,0.8706
2,687de7719a7947bf4361d2f6,MGNT,https://realty.rbc.ru/news/687de7719a7947bf436...,«Неформат» делюкс: как меняется интерес к редк...,2025-07-23 10:00:00,Еще тридцать лет назад пределом жилищных мечта...,Жилье,0.6657,0.1671,0.1671
3,694d4eb69a79472f0e375128,MGNT,https://pro.rbc.ru/demo/694d4eb69a79472f0e375128,На просадке. Какие акции на многолетних миниму...,2026-01-05 08:00:00,NaN,Не определена,NaN,NaN,NaN
4,6786082c9a79471a477cf524,MGNT,https://kavkaz.rbc.ru/kavkaz/freenews/6786082c...,Аналитики БКС: выплаты на акцию «Магнита» сост...,2025-01-14 09:46:34,"Брокер «БКС Мир инвестиций» ожидает, что разме...",Не определена,0.0862,0.0862,0.8277
...,...,...,...,...,...,...,...,...,...,...
1494,kak-v-25-raza-uvelichit-prodazhi-produktov-iz-...,MGNT,https://companies.rbc.ru/news/yMvU415bxf/kak-v...,Как в 2.5 раза увеличить продажи продуктов из ...,NaN,NaN,Не определена,NaN,NaN,NaN
1495,68f7bd589a794712a0de230f,MGNT,https://kuban.rbc.ru/krasnodar/freenews/68f7bd...,РБК ТВ Юг: оборот e-commerce на Дону вырос поч...,2025-10-22 06:50:00,Медиа Группа РБК Юг и Северный Кавказ и телека...,Не определена,0.7290,0.1355,0.1355
1496,66fc1e899a79475de9b0146d,MGNT,https://www.rbc.ru/quote/news/article/66fc1e89...,Акции «Магнита» упали почти на 7%. Инвесторы ж...,2024-10-01 20:13:34,"Акции ретейлера«Магнит»на торгах во вторник, 1...",Новости,0.2372,0.5256,0.2372
1497,694119b69a7947b58bc9763b,MGNT,https://www.rbc.ru/rbcfreenews/694119b69a7947b...,ФАС проверит причины высоких наценок на отдель...,2025-12-16 12:55:11,Федеральная антимонопольная служба (ФАС) прове...,Не определена,0.0863,0.0863,0.8273
1498,buduschee-otelnogo-biznesa-tsifrovizatsiya-ust...,MGNT,https://companies.rbc.ru/news/NY6a8L3oQ7/budus...,"Будущее отельного бизнеса: цифровизация, устой...",NaN,NaN,Не определена,NaN,NaN,NaN

In [6]:
e = pd.read_csv('rbc_MGNT.csv')
e

,news_id,ticker,url,title,published_at,text,category,sentiment_positive,sentiment_negative,sentiment_neutral
0,66964cad9a79476dfa199c2a,LKOH,https://www.rbc.ru/business/16/07/2024/66964ca...,Волож вернулся на пост главы бывшего Yandex N.V.,2024-07-16 13:47:14,"Нидерландская компания Yandex N.V., которая на...",Продажа российского «Яндекса»,0.1316,0.1316,0.7367
1,64bfd34f9a7947435d449447,LKOH,https://pro.rbc.ru/demo/64bfd34f9a7947435d449447,Нефть дорожает. Акции каких компаний будут рас...,2023-07-26 11:04:34,NaN,Не определена,NaN,NaN,NaN
2,678118569a79473c4b2b5aa8,LKOH,https://www.rbc.ru/industries/news/678118569a7...,Цифровые двойники и IoT: как технологии меняют...,2025-01-10T16:16:07.000,В последние годы нефтегазовый сектор столкнулс...,Не определена,0.0375,0.0375,0.9250
3,660bf47c9a79478dc6c5c58a,LKOH,https://www.rbc.ru/business/02/04/2024/660bf47...,Forbes назвал богатейшего бизнесмена России и ...,2024-04-02 15:13:17,Основатель нефтяной компании ЛУКОЙЛ Вагит Алек...,Бизнес,0.1344,0.1344,0.7311
4,697b133d9a794732abb15735,LKOH,https://kaliningrad.rbc.ru/kaliningrad/29/01/2...,Литва запретила въезд грузовикам из РФ с более...,2026-01-29 11:00:33,Правительство Литвы запретило въезд на террито...,Калининград,0.1340,0.7319,0.1340
...,...,...,...,...,...,...,...,...,...,...
1495,5e2044559a7947497f0c4340,LKOH,https://www.rbc.ru/quote/news/training/5e20445...,10 главных терминов фондового рынка: что нужно...,2025-10-14 18:14:35,Содержание: Под словом «инвестиции» можно пони...,Академия,0.0816,0.0816,0.8369
1496,660bb3bf9a7947156799115a,LKOH,https://www.rbc.ru/politics/02/04/2024/660bb3b...,Bloomberg узнал об опасениях жителей города Бо...,2024-04-02 11:30:46,Жители города Камено в Бургасской области Болг...,Политика,0.1043,0.1043,0.7913
1497,67e2bd2c9a7947748ac7d57a,LKOH,https://pro.rbc.ru/demo/67e2bd2c9a7947748ac7d57a,Как защитить портфель в период турбулентности:...,2025-03-27 08:50:25,NaN,Не определена,NaN,NaN,NaN
1498,658bd4ce9a794706067a24d0,LKOH,https://perm.rbc.ru/perm/freenews/658bd4ce9a79...,В Прикамье возбуждено дело из-за повышения цен...,2023-12-27 10:40:43,Пермское УФАС возбудило дело в отношении ООО «...,Пермь,0.1204,0.7592,0.1204
1499,67d2b6809a794700676defeb,LKOH,https://www.rbc.ru/rbcfreenews/67d2b6809a79470...,Три дерби за два дня. Чего ждать от тура РПЛ,2025-03-15 09:01:32,В прошлом туре футболисты московского «Локомот...,Спорт,0.1980,0.1980,0.6041

In [7]:
f = pd.read_csv('rbc_MTSS.csv')
f

,news_id,ticker,url,title,published_at,text,category,sentiment_positive,sentiment_negative,sentiment_neutral
0,68dfab699a79472bb5821a18,GAZP,https://www.rbc.ru/business/03/10/2025/68dfab6...,В Болгарии одобрили продажу АЗС под брендом «Г...,2025-10-03 14:37:12,Власти Болгарии разрешили сербской NIS продать...,Не определена,0.0541,0.0541,0.8917
1,6937c3fa9a79477d138242ec,GAZP,https://kavkaz.rbc.ru/kavkaz/freenews/6937c3fa...,Жители части Махачкалы остались без газоснабже...,2025-12-09 09:39:30,Жители Кировского и части Советского районов М...,Не определена,0.1234,0.1234,0.7533
2,mihail-konstantinov-za-godyi-rabotyi-nashi-kli...,GAZP,https://companies.rbc.ru/news/XoCCPm5VyH/mihai...,Михаил Константинов: «За годы работы наши клие...,NaN,NaN,Не определена,NaN,NaN,NaN
3,690d99719a7947f42b9efe3b,GAZP,https://rt.rbc.ru/tatarstan/10/11/2025/690d997...,Татарстан лидирует в России по инновационной а...,2025-11-10 09:06:48,В Татарстане в январе-сентябре 2025 года подал...,Не определена,0.1813,0.1813,0.6373
4,68f9fcf67a8aa984d92b9495,GAZP,https://spb.plus.rbc.ru/pressrelease/68f9fcf67...,«Оператор Газпром ИД» и проект «Твой Ход» объя...,2025-10-23 13:17:07,Партнерство направлено на развитие профессиона...,Пресс-релизы,0.1550,0.1550,0.6901
...,...,...,...,...,...,...,...,...,...,...
1491,692070609a79479880ddf2c5,GAZP,https://pro.rbc.ru/demo/692070609a79479880ddf2c5,Что будет с бизнесом и акциями ЛУКОЙЛа в услов...,2025-11-25 08:00:00,NaN,Не определена,NaN,NaN,NaN
1492,685acb669a7947ae3f19ae56,GAZP,https://www.rbc.ru/politics/24/06/2025/685acb6...,Пашинян заявил о «неудавшемся госперевороте мо...,2025-06-24 19:47:08,«Мошенники» намеревались осуществить в Армении...,Не определена,0.2351,0.2351,0.5297
1493,6800dbee9a7947d90a150d3c,GAZP,https://www.rbc.ru/business/18/04/2025/6800dbe...,Суд наложил арест на бывший склад чешской PPF ...,2025-04-18 09:00:16,Фрунзенский районный суд Петербурга в середине...,Не определена,0.1082,0.7835,0.1082
1494,68d67cda7a8aa9f11730ad55,GAZP,https://karelia.plus.rbc.ru/pressrelease/68d67...,«Петербургтеплоэнерго» подготовилось к отопите...,2025-09-26 17:08:54,ООО «Петербургтеплоэнерго» завершило подготовк...,Пресс-релизы,0.1688,0.1688,0.6623
1495,69a15cec9a7947127921433a,GAZP,https://www.rbc.ru/quote/news/article/69a15cec...,ГПБ снизил ставки по накопительным счетам,2026-02-27 12:16:01,С 28 февраля Газпромбанк снизит ставки по неко...,РБК Банки,0.0401,0.0401,0.9199

In [8]:
g = pd.read_csv('rbc_ROSN.csv')
g

,news_id,ticker,url,title,published_at,text,category,sentiment_positive,sentiment_negative,sentiment_neutral
0,nsk-na-pmgf-ot-postavschika-k-strategicheskomu...,ROSN,https://companies.rbc.ru/news/xF5y8JOGkn/nsk-n...,НСК на ПМГФ: от поставщика к стратегическому п...,NaN,NaN,Не определена,NaN,NaN,NaN
1,68fa04419a7947db12eb6b6e,ROSN,https://www.rbc.ru/rbcfreenews/68fa04419a7947d...,Захарова ответила на новые санкции США словами...,2025-10-23 14:14:01,Решение США ввести санкции против российских к...,Не определена,0.1731,0.6539,0.1731
2,620611b69a794741d09ea1e4,ROSN,https://www.rbc.ru/quote/news/article/620611b6...,«Роснефть» сообщила о шестикратном росте чисто...,2022-02-11 12:04:22,Чистая прибыль«Роснефти»по МСФО в 2021 году вы...,Новости,0.2045,0.2045,0.5911
3,6409328b9a794764957a3141,ROSN,https://www.rbc.ru/politics/09/03/2023/6409328...,Суд в США выдал ордер на арест «самолета «Росн...,2023-03-09 09:30:46,Окружной суд восточного округа Нью-Йорка санкц...,Не определена,0.0939,0.8122,0.0939
4,63a1de909a7947b16ad0d560,ROSN,https://www.rbc.ru/business/20/12/2022/63a1de9...,«Транснефть» опровергла переговоры с Казахстан...,2022-12-20 20:22:21,«Транснефть»: Казахстан не обращался к компани...,Не определена,0.1324,0.1324,0.7352
...,...,...,...,...,...,...,...,...,...,...
1494,663773279a79471fc0ca9696,ROSN,https://ufa.rbc.ru/ufa/05/05/2024/663773279a79...,Подрядчик взыскал с «Башнефти» 13 млн из-за ср...,2024-05-05 14:55:34,Компания «Енер-холдинг» взыскала с ПАО «Башнеф...,Не определена,0.1862,0.6276,0.1862
1495,67c6e2b39a79479cef275ad7,ROSN,https://www.rbc.ru/business/04/03/2025/67c6e2b...,Суд арестовал активы железнодорожных операторо...,2025-03-04 22:04:13,Октябрьский районный суд Екатеринбурга арестов...,Не определена,0.0697,0.0697,0.8606
1496,667e3e569a79476cde98bf1b,ROSN,https://www.rbc.ru/quote/news/article/667e3e56...,"Укрепление рубля, дивиденды «Сургутнефтегаза» ...",2024-06-28 09:20:26,Курс китайского юаня на Московской бирже на то...,События дня,0.0556,0.0556,0.8889
1497,645458989a7947cb23cba39e,ROSN,https://www.rbc.ru/politics/05/05/2023/6454589...,"«Ведомости» узнали, что власти обсудят возврат...",2023-05-05 04:52:54,«Ведомости»: правительство обсудит с бизнесом ...,Не определена,0.1475,0.1475,0.7050
1498,64c3c9499a7947cbb605fad8,ROSN,https://www.rbc.ru/politics/28/07/2023/64c3c94...,На заводе по переработке нефти в Самаре произо...,2023-07-28 16:59:30,Депутат Хинштейн: на нефтеперерабатывающем зав...,Не определена,0.1553,0.6894,0.1553

In [9]:
h = pd.read_csv('rbc_SBER.csv')
h

,news_id,ticker,url,title,published_at,text,category,sentiment_positive,sentiment_negative,sentiment_neutral
0,67b5f8889a7947d8d324cb63,ALRS,https://www.rbc.ru/quote/news/article/67b5f888...,В «Айгенис» назвали бенефициаров снятия санкци...,2025-02-20 14:15:01,Материал носит исключительно ознакомительный х...,Новости,0.0375,0.0375,0.9249
1,5c626b8f9a7947c5fa8162e3,ALRS,https://www.rbc.ru/quote/news/article/5c626b8f...,МосБиржа отыгрывает внешний позитив. Надолго л...,2019-02-12 10:11:16,Зарубежные рынки торгуются в «зеленой зоне» пе...,Не определена,0.0573,0.0573,0.8854
2,5f685a8d9a794726b42289cc,ALRS,https://www.rbc.ru/quote/news/investment_idea/...,Инвестидея: +35% на акциях алмазодобытчика АЛРОСА,2020-09-23 10:30:01,Закрытие границ и введение карантинных мер из-...,Инвестидеи,0.0722,0.0722,0.8555
3,5c220e8d9a794725de16bb99,ALRS,https://www.rbc.ru/business/26/12/2018/5c220e8...,Аудиторы предупредили о рисках роста энерготар...,2018-12-26 09:06:05,Счетная палата (СП) увидела риски удорожания э...,Не определена,0.1889,0.1889,0.6223
4,6659cb029a79471c61bebd91,ALRS,https://www.rbc.ru/quote/news/article/6659cb02...,Брокер «ВТБ Мои Инвестиции» обновил топ-10 рос...,2024-05-31 17:16:33,Аналитики брокера «ВТБ МоиИнвестиции» обновили...,Новости,0.2116,0.2116,0.5769
...,...,...,...,...,...,...,...,...,...,...
1492,66f6baff9a794758454bd04b,ALRS,https://www.rbc.ru/quote/news/article/66f6baff...,"«Больно, но не смертельно»: что беспокоит бизн...",2024-09-29 10:10:18,X5 Retail Groupпроживает удачный момент с точк...,Что это значит,0.1247,0.1247,0.7505
1493,5ae098a92ae5961b67a1da82,ALRS,https://www.rbc.ru/quote/news/article/5ae098a9...,Настроения на рынках могут ухудшиться,2017-10-05 14:34:35,«Очередной день спокойствия наблюдается на все...,Не определена,0.1949,0.1949,0.6102
1494,67a25ab19a79475a7e867d9d,ALRS,https://pro.rbc.ru/demo/67a25ab19a79475a7e867d9d,«Недовешенные» гиганты: какие российские акции...,2025-02-06 08:11:15,NaN,Не определена,NaN,NaN,NaN
1495,v-tass-sostoyalos-ofitsialnoe-otkryitie-xiv-se...,ALRS,https://companies.rbc.ru/news/O8dn0D2bZR/v-tas...,В ТАСС состоялось официальное открытие XIV сез...,NaN,NaN,Не определена,NaN,NaN,NaN
1496,64e25c139a7947e80078cc95,ALRS,https://www.rbc.ru/quote/news/article/64e25c13...,"Акции «Группы Позитив», дивиденды АЛРОСА и реш...",2023-08-21 09:10:56,"«Группа Позитив», также известная как Positive...",События дня,0.1066,0.1066,0.7867

In [10]:
i = pd.read_csv('rbc_VTBR.csv')
i

,news_id,ticker,url,title,published_at,text,category,sentiment_positive,sentiment_negative,sentiment_neutral
0,68af0ec39a79477bbf016655,VTBR,https://www.rbc.ru/quote/news/article/68af0ec3...,ЦБ зарегистрировал проспект акций «Дом.РФ» в п...,2025-08-27 18:19:57,Банк России зарегистрировал проспект обыкновен...,Новости,0.0466,0.0466,0.9067
1,6920690f9a79470a0a50d8f1,VTBR,https://realty.rbc.ru/news/6920690f9a79470a0a5...,"В МВД назвали число квартир, похищенных телефо...",2025-11-21 17:39:29,Единой по России статистики телефонного мошенн...,Отрасль,0.1328,0.1328,0.7344
2,686b8e299a794761262879ec,VTBR,https://realty.rbc.ru/news/686b8e299a794761262...,Семейная ипотека на строительство дома: как по...,2026-02-17 17:10:17,Семейная ипотека позволяет потратить льготный ...,Деньги,0.1035,0.1035,0.7929
3,694948659a7947219b17bc92,VTBR,https://www.rbc.ru/quote/news/article/69494865...,Т-банк изменил ставки по вкладам после заседан...,2025-12-22 16:44:44,С 23 декабря Т-банк изменил ставки по вкладам ...,РБК Банки,0.0454,0.0454,0.9093
4,68fb4f479a79473dd34a00a3,VTBR,https://rt.rbc.ru/tatarstan/freenews/68fb4f479...,В ВТБ прогнозировали сохранение ключевой ставки,2025-10-24 13:25:24,Сегодня состоялось заседание совета директоров...,Не определена,0.0362,0.0362,0.9276
...,...,...,...,...,...,...,...,...,...,...
694,68e8a7ed9a794743b4132305,VTBR,https://www.rbc.ru/quote/news/article/68e8a7ed...,Цена на серебро впервые в истории превысила $5...,2025-10-13 16:02:53,Биржевые цены на серебро снова обновили истори...,Новости,0.1815,0.1815,0.6371
695,698c963b9a794797c852c796,VTBR,https://realty.rbc.ru/news/698c963b9a794797c85...,В России установлен январский рекорд продаж но...,2026-02-11 18:53:35,В январе 2026 года российские застройщики прод...,Жилье,0.2421,0.2421,0.5158
696,68abe8149a7947b49001e689,VTBR,https://www.rbc.ru/quote/news/article/68abe814...,"Коррекция акций и ОФЗ, дивиденды «Газпром нефт...",2025-08-25 09:07:41,"По итогам основных торгов в пятницу, 22 август...",События дня,0.1091,0.1091,0.7817
697,689afb619a79472413df37e2,VTBR,https://www.rbc.ru/rbcfreenews/689afb619a79472...,Врачи спасли подростка с разрывом печени после...,2025-08-12 11:48:12,В Видном врачи спасли подростка с разрывом печ...,Не определена,0.0758,0.0758,0.8484
698,6967aa4e7a8aa94ffa1a6466,VTBR,https://kuban.plus.rbc.ru/partners/6967aa4e7a8...,Хоум-офис с видом на побережье и стабильный ви...,2026-01-15 13:43:53,Серые зимы и бесконечные пробки в мегаполисах ...,Новости партнеров,0.1091,0.1091,0.7819

In [11]:
data = pd.concat([a, b, c, d, e, f, g,h, i], ignore_index=True)

In [12]:
data

,news_id,ticker,url,title,published_at,text,category,sentiment_positive,sentiment_negative,sentiment_neutral
0,mts-bank-private-voshel-v-spisok-luchshih-bank...,MTSS,https://companies.rbc.ru/news/H0nXAx8uGq/mts-b...,МТС Банк Private вошел в список лучших банков ...,NaN,NaN,Не определена,NaN,NaN,NaN
1,685023957a8aa93a0103b841,MTSS,https://spb.plus.rbc.ru/news/685023957a8aa93a0...,Структурная перезагрузка,2025-06-17 16:16:19,В географически и логистически оторванном от к...,Тенденции,0.0798,0.0798,0.8404
2,67cacfbd9a79472db2261dbd,MTSS,https://www.rbc.ru/life/news/67cacfbd9a79472db...,"Каждый четвертый мужчина уверен, что не поздра...",2025-03-07 11:06:23,"SuperJob: каждый четвертый мужчина уверен, что...",Не определена,0.1506,0.1506,0.6988
3,67ee2b879a79474dd13bb3db,MTSS,https://pro.rbc.ru/demo/67ee2b879a79474dd13bb3db,Краха не избежать. Почему массовые увольнения ...,2025-04-08 07:01:07,NaN,Не определена,NaN,NaN,NaN
4,67cad2619a79473aaa0f2a5b,MTSS,https://www.rbc.ru/quote/news/article/67cad261...,Брокеры составили портрет среднестатистической...,2025-03-08 09:00:22,Российские женщины-инвесторы оказались успешне...,Новости,0.1065,0.1065,0.7871
...,...,...,...,...,...,...,...,...,...,...
12677,68e8a7ed9a794743b4132305,VTBR,https://www.rbc.ru/quote/news/article/68e8a7ed...,Цена на серебро впервые в истории превысила $5...,2025-10-13 16:02:53,Биржевые цены на серебро снова обновили истори...,Новости,0.1815,0.1815,0.6371
12678,698c963b9a794797c852c796,VTBR,https://realty.rbc.ru/news/698c963b9a794797c85...,В России установлен январский рекорд продаж но...,2026-02-11 18:53:35,В январе 2026 года российские застройщики прод...,Жилье,0.2421,0.2421,0.5158
12679,68abe8149a7947b49001e689,VTBR,https://www.rbc.ru/quote/news/article/68abe814...,"Коррекция акций и ОФЗ, дивиденды «Газпром нефт...",2025-08-25 09:07:41,"По итогам основных торгов в пятницу, 22 август...",События дня,0.1091,0.1091,0.7817
12680,689afb619a79472413df37e2,VTBR,https://www.rbc.ru/rbcfreenews/689afb619a79472...,Врачи спасли подростка с разрывом печени после...,2025-08-12 11:48:12,В Видном врачи спасли подростка с разрывом печ...,Не определена,0.0758,0.0758,0.8484
12681,6967aa4e7a8aa94ffa1a6466,VTBR,https://kuban.plus.rbc.ru/partners/6967aa4e7a8...,Хоум-офис с видом на побережье и стабильный ви...,2026-01-15 13:43:53,Серые зимы и бесконечные пробки в мегаполисах ...,Новости партнеров,0.1091,0.1091,0.7819

In [13]:
data.isna().sum()

news_id                  0
ticker                   0
url                      0
title                    0
published_at          1744
text                  2944
category                 0
sentiment_positive    2944
sentiment_negative    2944
sentiment_neutral     2944
dtype: int64

In [15]:
data.to_csv('all_data.csv', index=False, encoding='utf-8-sig')